### ISSUE TITLE
how to add standalone view

### ISSUE THREAD

**Issue by ommyan** [jonalxh/Flask-Admin-Dashboard#1]
dear Jonalxh,

i tried to develop app from your boilerplate, this is a great boilerplate. i have a problem , how to add a standalone view, i followed this documentation : 
```
`from flask_admin import BaseView, expose

class AnalyticsView(BaseView):
    @expose('/')
    def index(self):
        return self.render('analytics_index.html')

admin.add_view(AnalyticsView(name='Analytics', endpoint='analytics'))`
```

and in analytics_index.html i write code below

```
`{% extends 'admin/master.html' %}
{% block body %}
  <p>Here I'm going to display some data.</p>
{% endblock %}`
```

i sad, i get error : 
`Exception: Attempted to instantiate admin view AnalyticsView without default view`

may i know, step by step how to add a standalone view

thank you verrymuch

**Comment by jonalxh** [comment]
Hi friend.

In theory your process is well done.

In addition of your code I've added **{{ super() }}** after **body block** instance, i.e in your analytics_index.html:

```
{% extends 'admin/master.html' %}
{% block body %}
{{ super() }}
    <p>Here I'm going to display some data.</p>
{% endblock body %}
```

It should work.

I've updated the repository adding a custom view item in the left menu, which redirects to a custom html view without DB model dependence, please pull the project and try to test it.

Let me know if it works for you.

**Comment by ommyan** [comment]
dear Jonalxh,

thank for quick response, this work like charm,...

salut

**Comment by jonalxh** [comment]
I'm glad to know that it works correctly.

I procceed to close the issue.

**Comment by ommyan** [comment]
closed
