### ISSUE TITLE
Can't sign-in

### ISSUE THREAD

**Issue by Serena123lasine** [jonalxh/Flask-Admin-Dashboard#10]
Hi , i can't sign-in , can i get some help, please?

sqlalchemy.exc.OperationalError
OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: INSERT INTO user (first_name, last_name, email, password, active, confirmed_at) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: (None, None, u'sxxx@gmail.com', '$pbkdf2-sha512$25000$LmVsba11rjWGMCYkhNBaCw$aCzQtJhP1Vyw4HUzJfsUVt0ZqCTWLNEekGXvMEl9e4y2FqbbThS5KRUjyKNcz2NaPnANyypeL3/62nbvAR83Sw', 1, None)]
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by jonalxh** [comment]
Hi.
The error says it is a readonly Database, try creating DB again or GRANT permissions to login and write to your DB user.

**Comment by Serena123lasine** [comment]
Hi , how can do it ? i'm still beginner with Flask

**Comment by jonalxh** [comment]
It is not about Flask, the problem is regarding to your DB provider.

**Comment by Serena123lasine** [comment]
okay , i used your sample data base , i wanna try to search , thank u so much

**Comment by Serena123lasine** [comment]
sudo chmod a+w dbname.sqlite

**Comment by Serena123lasine** [comment]
thank u.
