### ISSUE TITLE
Setting password for Users

### ISSUE THREAD

**Issue by atulnarayanan** [jonalxh/Flask-Admin-Dashboard#12]
I created a user from the admin dashboard as admin but there's no option to set password for the user and hence i can't login with the said user. Any fix for this?

**Comment by jonalxh** [comment]
Hi @DeStiNi10 you're right, I've checked and I've pushed a new version solving this issue, password field was added to create and edit form, by now it is an input type text, i'll solve it soon.

**Comment by atulnarayanan** [comment]
Thank you very much! I'll follow up when you solve it. Could you just give a notification on this thread once you solve it?

**Comment by jonalxh** [comment]
Yes, I'll comment here when solved.

**Comment by jonalxh** [comment]
@DeStiNi10 It is now solved, please pull the repo and it'll be done.

**Comment by atulnarayanan** [comment]
Thank you very much!
