### ISSUE TITLE
how to customize admin/index.html ?

### ISSUE THREAD

**Issue by MinkyuHa** [jonalxh/Flask-Admin-Dashboard#4]
Hello.
Thanks for your fancy dash board .
Let me ask you one thing about front page UI.

I'd like to customize the front UI dashboard (graph, chat, todo ..etc) from admin/index.html .
Therefore I need to implement the flask code which get some values from database,
and then 
render_template('admin/index.html', some_value='blah blah')

However I cannot find the way to access this template html from flask backend.

Thanks for your support in advance.

**Comment by jonalxh** [comment]
Hi @MinkyuHa 

- I've found [this example](https://gist.github.com/marteinn/5546293) where they override the AdminIndexView.

- Have you tried the custom index? There I've written an independent html file which doesn't need flask-admin, inside the function referenced below you could make your DB queries an then pass the values you want.
https://github.com/jonalxh/Flask-Admin-Dashboard/blob/5f5a9b9574e9470d5db76454e8f49a9cb55290c8/app.py#L97-L101

- If this is not what you're looking for, I recommend you to give a look to **flask-admin context processor** in [this link](http://flask.pocoo.org/docs/1.0/templating/#context-processors), at the moment I've not free time to help you with a working example, but let me know if you get it with my recommendations.

**Comment by MinkyuHa** [comment]
Hi @jonalxh 
Thanks for your comment.
of course, I know how to add the custom view from your example.
However it's for adding the menu from left panel.

What I'm looking for is that customizing the first page which users see at first time. ==> admin/index.html  . 
I can see that this file is showing the graph,  chart, etc.
This seems not to be customized from  admin.add_view(....)

Meanwhile, I'll check the flask-admin context processor.

Thank you.

**Comment by jonalxh** [comment]
Look at the first item of my answer above, I think it will work for you.

**Comment by MinkyuHa** [comment]
Oh, I missed it. Thank you very much. I'll try.
