### ISSUE TITLE
browsing Flask-Admin-Dashboard in mobile is very slow

### ISSUE THREAD

**Issue by earnestman** [jonalxh/Flask-Admin-Dashboard#5]
hi
i run Flask-Admin-Dashboard in raspberry pi and make a hotspot by hostapd to other mobile can connect to my raspberry. but my big problem is that when i want to browse project in mobile browser that connected to raspberry by wifi, the Dashboard is very slow and every page take avg 40 seconds to load!!

can you help me?

**Comment by jonalxh** [comment]
Hi.
There's nothing I can do, it is related to Flask and Flask-Admin projects, I was just implementing a Dashboard template, navigation speed is not affected by this.
