### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by dhandeo** [jonalxh/Flask-Admin-Dashboard#7]
Thanks for open sourcing this. There is so much to learn from this wonderful effort. Would you consider releasing it with some oss compatible license ? mit or apache comes to mind.  Thank you.

**Comment by jonalxh** [comment]
Hi. I'm not a license expert and my only wish was to share it with the community, Is there any reason why I should do it?

**Comment by dhandeo** [comment]
https://medium.com/glitch/why-add-a-license-to-your-open-source-project-6f07941f9288

**Comment by jonalxh** [comment]
Thanks, there was a lot of info I didn't know, I've setted a license now.
