### ISSUE TITLE
Boolean fields shows as a textfield 

### ISSUE THREAD

**Issue by kartikdani** [jonalxh/Flask-Admin-Dashboard#8]
![Screen Shot 2020-04-06 at 4 28 28 PM](https://user-images.githubusercontent.com/52491784/78551713-c5721d00-7823-11ea-9358-4906959b03f8.png)
I tried for the flask admin dashboard in my DB I have many boolean fields but it not showing as a checkbox it's showing as a simple text box. I don't know how to enter a value in that.

**Comment by jonalxh** [comment]
Hi, I'll check it on weekend.
It should be working fine.

**Comment by giovannipiccinelli** [comment]
@jonalxh I am experiencing the same issue. Did u have time to check? Btw thanks for the awesome work!

**Comment by moscovig** [comment]
Having the same issue
It gets fine when disabling    .form-control:not(select)  class
Thanks for this amazing project

**Comment by jonalxh** [comment]
Hi everyone, I'm currently finishing a project and in a couple weeks i'll be trying to fix it.

**Comment by jonalxh** [comment]
Just to know. Are you using requirements.txt dependencies version or installing it updated?

**Comment by jonalxh** [comment]
Hi everyone, after a lot of research I've found it works if you set `template_mode='bootstrap4'` instead of `bootstrap3` in `app.py` file. I've updated the repo for you to see how does it looks like now.
